import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import "./globals.css";

const poppins = Inter({
    subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased flex h-full flex-col`}>
        <Header />
        <main>
            {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
